name: Build container

on:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build container
        run: |
          docker build \
          --build-arg git_sha=$GITHUB_SHA \
          -t platform-mvp/ircc:$GITHUB_SHA \
          -f ./wordpress/docker/production.Dockerfile .
