name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "wordpress/**"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "wordpress/**"

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    name: Cypress
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - run: cd wordpress && composer install --prefer-dist --no-progress --no-suggest
      - run: npm install
      - run: cd wordpress/wp-content/mu-plugins/cds-base && npm run wp-env:init
      - run: cd wordpress/wp-content/mu-plugins/cds-base && npm run cy:run
  php-tests:
    runs-on: ubuntu-latest
    name: PHP Pest tests
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - run: cd wordpress && composer install --prefer-dist --no-progress --no-suggest
      - run: cd wordpress && ./vendor/bin/pest
  phpcs:
    runs-on: ubuntu-latest
    name: Code quality
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: phpcs, cs2pr
      - name: Run PHP Code Sniffer
        run: phpcs wordpress -n --standard=PSR12 --ignore=vendor,tests,*.css,*.js
